### ISSUE TITLE
Error building project

### ISSUE THREAD

**Issue by narner** [tikimcfee/LookAtThat#1]
<img width="478" alt="CleanShot 2022-05-25 at 11 32 50" src="https://user-images.githubusercontent.com/2131591/170341432-8d502b1a-bd7c-4931-a967-934905ce519f.png">

**Comment by tikimcfee** [comment]
Wait. Wait. _Now_ try it with https://github.com/tikimcfee/LookAtThat/commit/bc0406f8ca6b5373a48cc2f954650bc667ed1bc2
